name: Manual builder

on:
  workflow_dispatch:

jobs:
  windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install certifi
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller
        git checkout tags/v4.1
        cd bootloader
        python waf all
        cd ..
        pip install -e .
    - name: Build binary
      run: pyinstaller --additional-hooks-dir=Hooks/ -y -F -i CurseBreaker.ico -n CurseBreaker -c --noupx --exclude-module FixTk --exclude-module tcl --exclude-module tk --exclude-module _tkinter --exclude-module tkinter --exclude-module Tkinter CurseBreaker.py
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: Windows
        path: dist/CurseBreaker.exe
